# Generated by Django 3.0.8 on 2020-07-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=6, unique=True)),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('note', models.TextField()),
                ('referrer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'referral',
            },
        ),
    ]
